# This file is a template, and might need editing before it works on your project.
# This template uses the non default language docker image
# The image already has Hex installed. You might want to consider to use `elixir:latest`
image: trenpixster/elixir:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-service
services:
  - postgres:latest
  
variables:
  POSTGRES_DB: business_process_web_portal_dev

test:
  script:
  - mix deps.get
  - mix test --cover
